### ISSUE TITLE
Could not fetch model of type 'IdeaProject'

### ISSUE THREAD

**Issue by sbtourist** [kelemen/netbeans-gradle-project#191]
I'm using NetBeans 8.0.2 with the latest Gradle plugin, configured with the Idea-based mode and using `?DIST=https://services.gradle.org/distributions/gradle-2.2.1-all.zip` as the Gradle installation dir. I'm recently getting the following exception, after the gradle wrapper has been upgraded to 2.3:

org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.2.1-all.zip'.
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:53)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:48)
	at org.netbeans.gradle.project.model.NbCompatibleModelLoader.getModelWithProgress(NbCompatibleModelLoader.java:90)
	at org.netbeans.gradle.project.model.NbCompatibleModelLoader.loadMainModel(NbCompatibleModelLoader.java:212)
	at org.netbeans.gradle.project.model.NbCompatibleModelLoader.loadModels(NbCompatibleModelLoader.java:67)
	at org.netbeans.gradle.project.model.GradleModelLoader.loadModelWithProgress(GradleModelLoader.java:503)
	at org.netbeans.gradle.project.model.GradleModelLoader.access$600(GradleModelLoader.java:63)
	at org.netbeans.gradle.project.model.GradleModelLoader$6.run(GradleModelLoader.java:372)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:36)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:23)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:126)
	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:905)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:884)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:798)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:813)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:847)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/sergio/Dev/Lab/datastax/dse-master/dse-search/build.gradle' line: 4
A problem occurred evaluating root project 'dse-search'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:77)
	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:108)
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:97)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.configure(InProcessBuildActionExecuter.java:84)
	at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:45)
	at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:30)
	at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'dse-search'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	... 32 more
Caused by: org.gradle.api.UnknownProjectException: Project with path ':dse-core' could not be found in root project 'dse-search'.
	at org.gradle.api.internal.project.AbstractProject.project(AbstractProject.java:450)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:225)
	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:129)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_dnxkfko8ruaoyz0woyi1k3ila$_run_closure1.doCall(/Users/sergio/Dev/Lab/datastax/dse-master/dse-search/build.gradle:4)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
	at org.gradle.api.internal.project.AbstractProject.dependencies(AbstractProject.java:843)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:225)
	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:129)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_dnxkfko8ruaoyz0woyi1k3ila.run(/Users/sergio/Dev/Lab/datastax/dse-master/dse-search/build.gradle:3)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 43 more

**Comment by kelemen** [comment]
Given your stack trace, I would think that the error is in your build script. That is, your build script throws an exception when evaluated: `/Users/sergio/Dev/Lab/datastax/dse-master/dse-search/build.gradle:4`. If you have specified the Gradle distribution to use explicitly (as you have said), the Gradle wrapper is irrelevant.

**Comment by sbtourist** [comment]
But then why does it work on the command line? It even works on Idea 14.1.

**Comment by kelemen** [comment]
What is your project's structure? That is, where are all the build.gradle and settings.gradle files? That is, if you can "cd" any of your subproject directory and successfully run "gradle tasks" from there, then I believe NetBeans should work as well. Anyway, can you give me a project with which I can reproduce the issue with?

**Comment by sbtourist** [comment]
I have a multi-module Gradle project with a build.gradle file on the main
module and each submodule. Any gradle commands work great by the command
line, but NetBeans is still unable to open the project without generating
the attached exception.

On Tue, Mar 31, 2015 at 3:30 PM, Attila Kelemen <notifications@github.com>
wrote:

> What is your project's structure? That is, where are all the build.gradle
> and settings.gradle files? That is, if you can "cd" any of your subproject
> directory and successfully run "gradle tasks" from there, then I believe
> NetBeans should work as well. Anyway, can you give me a project with which
> I can reproduce the issue with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kelemen/netbeans-gradle-project/issues/191#issuecomment-88110768>
> .
>



-- 
Sergio Bossa
http://www.linkedin.com/in/sergiob

**Comment by kelemen** [comment]
Can you provide an example project with which I can reproduce the issue with. To me it seems, that you may have a `settings.gradle` file lying around somewhere in the wrong location or the root project's directory is not the parent of all the subprojects. Are you sure that executing "gradle tasks" works fine from **each** subproject's directory?

**Comment by sbtourist** [comment]
You're right, "gradle tasks" only works on the main module.

All submodules fail with:
Project with path 'X' could not be found in root project 'Y'

And submodule X fails with a stackoverflow.

Still puzzled why Idea 14 is able to make the projcet work.

On Tue, Mar 31, 2015 at 5:42 PM, Attila Kelemen <notifications@github.com>
wrote:

> Can you provide an example project with which I can reproduce the issue
> with. To me it seems, that you may have a settings.gradle file lying
> around somewhere in the wrong location or the root project's directory is
> not the parent of all the subprojects. Are you sure that executing "gradle
> tasks" works fine from *each* subproject's directory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kelemen/netbeans-gradle-project/issues/191#issuecomment-88165492>
> .
>



-- 
Sergio Bossa
http://www.linkedin.com/in/sergiob

**Comment by kelemen** [comment]
As far as I know, Idea only loads the root project and works from there. This plugin treats subprojects as separate projects (except that they share their project properties).

**Comment by kelemen** [comment]
The most likely issue with your project is that there is a `settings.gradle` file in (at least) one of your subprojects.

**Comment by sbtourist** [comment]
The settings.gradle is in the main directory, does that matter?

On Tue, Mar 31, 2015 at 5:57 PM, Attila Kelemen <notifications@github.com>
wrote:

> The most likely issue with your project is that there is a settings.gradle
> file in (at least) one of your subprojects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kelemen/netbeans-gradle-project/issues/191#issuecomment-88171083>
> .
>



-- 
Sergio Bossa
http://www.linkedin.com/in/sergiob

**Comment by kelemen** [comment]
Thats good but I suspect that there might be another settings.gradle somewhere. Can you show the directory structure of your project (with only the settings.gradle and build.gradle files)?

**Comment by sbtourist** [comment]
There aren't any more, as 'find rootDir -iname "*settings*"' only returns
the main one.

On Tue, Mar 31, 2015 at 6:05 PM, Attila Kelemen <notifications@github.com>
wrote:

> Thats good but I suspect that there might be another settings.gradle
> somewhere. Can you show the directory structure of your project (with only
> the settings.gradle and build.gradle files)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kelemen/netbeans-gradle-project/issues/191#issuecomment-88172817>
> .
>



-- 
Sergio Bossa
http://www.linkedin.com/in/sergiob

**Comment by kelemen** [comment]
I'm not sure what the problem could be. Do you have a symlink somewhere in the paths? Also, still it would be best if I could see a reproducible example.

**Comment by sbtourist** [comment]
Turns out the project was not configured properly: each subproject had its own build.gradle, but some of those were not configured in the settings file as modules. Sorry about the time waste and thanks for assisting.
