### ISSUE TITLE
[8.1nightly] IAE - Attempted to pass a null directory to findProject

### ISSUE THREAD

**Issue by svenreimers** [kelemen/netbeans-gradle-project#222]
java.lang.IllegalArgumentException: Attempted to pass a null directory to findProject
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:159)
	at org.netbeans.gradle.project.properties.ProjectProfileSettings.tryGetProject(ProjectProfileSettings.java:65)
	at org.netbeans.gradle.project.properties.ProjectProfileSettings.saveNowUnsafe(ProjectProfileSettings.java:174)
	at org.netbeans.gradle.project.properties.ProjectProfileSettings.saveAndWait(ProjectProfileSettings.java:167)
	at org.netbeans.gradle.project.properties.ProjectProfileSettings$3.run(ProjectProfileSettings.java:159)
	at org.jtrim.concurrent.GenericUpdateTaskExecutor$PollAndExecuteTask.execute(GenericUpdateTaskExecutor.java:119)
[catch] at org.jtrim.concurrent.AbstractTaskExecutorService$1.execute(AbstractTaskExecutorService.java:142)
	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:919)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:898)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:815)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:827)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:861)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kelemen** [comment]
Given the stack trace, I guess that the project ceased to exist at some point. Is this the case? (i.e., did you delete the/a project?)
