### ISSUE TITLE
[1.3.7] Gradle plugin crashing NB 8.0.2 projects

### ISSUE THREAD

**Issue by hrstoyanov** [kelemen/netbeans-gradle-project#226]
My Bentbeans 8.0.2 IDE started crashing when opening project and debuigging. It turns out there is this message logged :
```
...
org.netbeans.gradle.project [1.3.7 1.3.7 201505240323]
org.netbeans.gradle.javaee.project [1.0.2 1.0.2 201412260256]
...
java.nio.file.InvalidPathException: UNC path is missing sharename: \\xyzinc.aaaaa.bbbbb.com
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:118)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at org.netbeans.gradle.project.NbGradleProjectFactory.isSafeToOpen(NbGradleProjectFactory.java:145)
	at org.netbeans.gradle.project.NbGradleProjectFactory.isProject(NbGradleProjectFactory.java:170)
	at org.netbeans.gradle.project.NbGradleProjectFactory.loadProject(NbGradleProjectFactory.java:210)
	at org.netbeans.api.project.ProjectManager.createProject(ProjectManager.java:371)
	at org.netbeans.api.project.ProjectManager.access$300(ProjectManager.java:86)
	at org.netbeans.api.project.ProjectManager$2.run(ProjectManager.java:292)
	at org.netbeans.api.project.ProjectManager$2.run(ProjectManager.java:235)
	at org.openide.util.Mutex.readAccess(Mutex.java:337)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:235)
	at org.netbeans.modules.projectapi.SimpleFileOwnerQueryImplementation.getOwner(SimpleFileOwnerQueryImplementation.java:144)
	at org.netbeans.modules.projectapi.SimpleFileOwnerQueryImplementation.getOwner(SimpleFileOwnerQueryImplementation.java:109)
	at org.netbeans.api.project.FileOwnerQuery.getOwner(FileOwnerQuery.java:133)
	at org.netbeans.modules.java.project.ProjectSourceForBinaryQuery.findSourceRoots2(ProjectSourceForBinaryQuery.java:79)
	at org.netbeans.api.java.queries.SourceForBinaryQuery.findSourceRoots2(SourceForBinaryQuery.java:126)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.createResources(PathRegistry.java:723)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.getSources(PathRegistry.java:294)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:4583)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5463)
[catch] at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3267)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:5810)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$5300(RepositoryUpdater.java:5476)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$3$1.run(RepositoryUpdater.java:5735)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:96)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$3.call(RepositoryUpdater.java:5731)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$3.call(RepositoryUpdater.java:5727)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:74)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:5727)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)


```

So my company mounts shared network drives to developer computers and the Gradle plugin somehow does not like the format \\\aaaa.bbbb.ccc.com

Diableing the Gradle plugin makes the IDE work normally again.

**Comment by kelemen** [comment]
I'll look int this. Give me a few days please.

**Comment by hrstoyanov** [comment]
Thanks kelemen,
My current workaround is to disable the plugin.

/Hristo Stoyanov

**Comment by kelemen** [comment]
I have fixed the crash but you still won't be able to open projects found on that location. Do you also have projects on such locations? Because that would a be a lot bigger issue to fix.

**Comment by hrstoyanov** [comment]
Thanks. I actually do not have projects on the network drive, not even sure
why NB8.0.2 is looking there. But the Gradle plugin is the only one
crashing.

Let me know when the fix has been published. Thanks again for the good work!

/Hristo Stoyanov

**Comment by kelemen** [comment]
I don't know when I will publish it but you can easily build the project for yourself. It should work out-of-the-box but for the best result read the instruction on the [wiki](https://github.com/kelemen/netbeans-gradle-project/wiki/Development)

**Comment by hrstoyanov** [comment]
Kelemen,
I saw you released 1.3.7.2 but is it for NB8.1Beta only, or will it also work for NB8.0.2?

I need a fix for this defect, #226 in NB8.0.2

Thanks.

**Comment by kelemen** [comment]
Since the NB dependencies changed incompatibly, if one version works for 8.1 it won't work for versions before that (and vice versa).

Though, I can release one for previous NB versions as well if you really need it. I'll do so this evening.

**Comment by hrstoyanov** [comment]
Thank you!

/Hristo Stoyanov

**Comment by kelemen** [comment]
I'm really sorry but I completely forgot about this. Hopefully I'll not today.

**Comment by kelemen** [comment]
Should be uploaded to http://plugins.netbeans.org/plugin/44510/gradle-support (though you might have to wait a few days before it is also available from the plugins window of NB). Sorry for the unnecessary delay.

**Comment by hrstoyanov** [comment]
Thank you!
