### ISSUE TITLE
"Compile on Save"-Option failes any non-Gradle projects

### ISSUE THREAD

**Issue by 38leinaD** [kelemen/netbeans-gradle-project#294]
When i enable "Compile on Save" under Options/Misc/Gradle/Other, all non-Gradle projects will fail to save any changes with the following exception:

java.lang.IllegalArgumentException: Not a Gradle project: C:\Users\daniel.platz\Documents\NetBeansProjects\netbeans-dev\CarSalesAnalysis@ec662d60:6000dcbb
	at org.netbeans.gradle.project.NbGradleProjectFactory.getGradleProject(NbGradleProjectFactory.java:61)
	at org.netbeans.gradle.project.java.tasks.CompileOnSaveAction.isGradleProject(CompileOnSaveAction.java:51)
	at org.netbeans.gradle.project.java.tasks.CompileOnSaveAction.performTask(CompileOnSaveAction.java:34)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable$1.run(BeforeSaveTasks.java:173)
	at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:356)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:156)
	at org.netbeans.gradle.project.java.tasks.CompileOnSaveAction.runLocked(CompileOnSaveAction.java:56)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:153)
	at org.netbeans.modules.editor.lib.TrailingWhitespaceRemove.runLocked(TrailingWhitespaceRemove.java:102)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:153)
	at org.netbeans.modules.editor.impl.ReformatBeforeSaveTask.runLocked(ReformatBeforeSaveTask.java:124)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:153)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks.runTasks(BeforeSaveTasks.java:130)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$2.run(BeforeSaveTasks.java:111)
	at org.openide.text.CloneableEditorSupport.saveDocumentImpl(CloneableEditorSupport.java:753)
	at org.openide.text.CloneableEditorSupport.saveDocument(CloneableEditorSupport.java:644)
	at org.netbeans.modules.properties.PropertiesEditorSupport.superSaveDoc(PropertiesEditorSupport.java:581)
	at org.netbeans.modules.properties.PropertiesEditorSupport$SaveImpl.run(PropertiesEditorSupport.java:1658)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:420)
	at org.netbeans.modules.properties.PropertiesEditorSupport.saveThisEntry(PropertiesEditorSupport.java:570)
	at org.netbeans.modules.properties.PropertiesEditorSupport.access$800(PropertiesEditorSupport.java:151)
	at org.netbeans.modules.properties.PropertiesEditorSupport$Environment.save(PropertiesEditorSupport.java:1033)
	at org.openide.actions.SaveAction.performAction(SaveAction.java:132)
	at org.openide.actions.SaveAction.performAction(SaveAction.java:102)
	at org.openide.actions.SaveAction$Delegate.actionPerformed(SaveAction.java:249)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:231)
	at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:260)
	at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:109)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:93)
	at org.openide.util.actions.ActionInvoker$ActionRunnable.actionPerformed(ActionInvoker.java:162)
	at org.netbeans.core.ModuleActions.invokeAction(ModuleActions.java:109)
	at org.netbeans.modules.openide.actions.ActionsBridgeImpl.invokeAction(ActionsBridgeImpl.java:60)
	at org.openide.util.actions.ActionInvoker$ActionRunnable.doRun(ActionInvoker.java:153)
	at org.openide.util.actions.ActionInvoker$2.run(ActionInvoker.java:110)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

Severity is low as i can simply disable this feature; and by default it is also disabled.

**Comment by kelemen** [comment]
Thanks for the report. It should be fixed in master now.

**Comment by 38leinaD** [comment]
awesome! :-)
