### ISSUE TITLE
NullPointerException in Gradle Projects (LibGDX) on Netbeans after latest Update to 1.3.9.1

### ISSUE THREAD

**Issue by CypherEA** [kelemen/netbeans-gradle-project#300]
Just updated this in Netbeans, now 

java.lang.NullPointerException
	at org.netbeans.gradle.project.java.model.JavaParsingUtils.getJarOutputs(JavaParsingUtils.java:253)
	at org.netbeans.gradle.project.java.model.JavaParsingUtils.parseModules(JavaParsingUtils.java:237)
	at org.netbeans.gradle.project.java.JavaExtensionDef.parseFromNewModels(JavaExtensionDef.java:76)
	at org.netbeans.gradle.project.java.JavaExtensionDef.parseModelImpl(JavaExtensionDef.java:109)
	at org.netbeans.gradle.project.java.JavaExtensionDef.parseModel(JavaExtensionDef.java:120)
[catch] at org.netbeans.gradle.project.extensions.NbGradleExtensionRef.parseModel(NbGradleExtensionRef.java:115)
	at org.netbeans.gradle.project.model.NbGradle18ModelLoader$ProjectModelParser.parseModel(NbGradle18ModelLoader.java:264)
	at org.netbeans.gradle.project.model.NbGradle18ModelLoader$ProjectModelParser.parseModel(NbGradle18ModelLoader.java:216)
	at org.netbeans.gradle.project.model.NbGradle18ModelLoader.loadModels(NbGradle18ModelLoader.java:81)
	at org.netbeans.gradle.project.model.DefaultGradleModelLoader.loadModelWithProgress(DefaultGradleModelLoader.java:550)
	at org.netbeans.gradle.project.model.DefaultGradleModelLoader.access$1500(DefaultGradleModelLoader.java:68)
	at org.netbeans.gradle.project.model.DefaultGradleModelLoader$7.run(DefaultGradleModelLoader.java:414)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:35)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:22)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:125)
	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:919)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:898)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:815)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:827)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:861)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kelemen** [comment]
See Issue #298. This was already fixed in master. So, for the time being, you either need to build the plugin from the sources or revert to version [1.3.8.1](http://dl.bintray.com/kelemen/maven/com/github/kelemen/netbeans-gradle-plugin/1.3.8.1/netbeans-gradle-plugin-1.3.8.1.nbm)

**Comment by CypherEA** [comment]
Thanks.

Sorry for the double post then. Didnt see it

בתאריך 20 באוק' 2016 21:00,‏ "Attila Kelemen" <notifications@github.com>
כתב:
