### ISSUE TITLE
When I add components to the form from the LGoodDatePicker library   an error

### ISSUE THREAD

**Issue by murads60** [kelemen/netbeans-gradle-project#345]
**When I add components to the form from the LGoodDatePicker library
  an error**

`java.lang.UnsupportedOperationException: Project in C:\rootProject\HelloProject of class org.netbeans.gradle.project.NbGradleProject has neither a ProjectClassPathModifierImplementation nor a ProjectClassPathExtender in its lookup
	at org.netbeans.api.java.project.classpath.ProjectClassPathModifier.findExtensible(ProjectClassPathModifier.java:400)
	at org.netbeans.api.java.project.classpath.ProjectClassPathModifier.addRoots(ProjectClassPathModifier.java:145)
	at org.netbeans.modules.nbform.project.ClassSourceResolver$JarEntry.addToProjectClassPath(ClassSourceResolver.java:194)
	at org.netbeans.modules.form.project.ClassSource.addToProjectClassPath(ClassSource.java:114)
	at org.netbeans.modules.form.project.ClassPathUtils$2.run(ClassPathUtils.java:270)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$ProgressBackgroundRunner.runBackground(RunOffEDTImpl.java:488)
	at org.netbeans.modules.progress.ui.AbstractWindowRunner.call(AbstractWindowRunner.java:108)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused: java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[catch] at org.netbeans.modules.progress.ui.RunOffEDTImpl.showProgressDialogAndRun(RunOffEDTImpl.java:384)
	at org.netbeans.api.progress.BaseProgressUtils.showProgressDialogAndRun(BaseProgressUtils.java:212)
	at org.netbeans.api.progress.ProgressUtils.showProgressDialogAndRun(ProgressUtils.java:237)
	at org.netbeans.modules.form.project.ClassPathUtils.updateProject(ClassPathUtils.java:266)
	at org.netbeans.modules.form.project.ClassPathUtils.updateProject(ClassPathUtils.java:238)
	at org.netbeans.modules.form.MetaComponentCreator.prepareClass(MetaComponentCreator.java:1439)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:258)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:298)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.init(HandleLayer.java:3369)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.<init>(HandleLayer.java:3361)
	at org.netbeans.modules.form.HandleLayer$NewComponentDropListener.dragEnter(HandleLayer.java:3658)
	at java.awt.dnd.DropTarget.dragEnter(DropTarget.java:358)
	at sun.awt.dnd.SunDropTargetContextPeer.processEnterMessage(SunDropTargetContextPeer.java:331)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEnterEvent(SunDropTargetContextPeer.java:799)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:767)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4744)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4676)
	at java.awt.LightweightDispatcher.trackDropTargetEnterExit(Container.java:4625)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4638)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4591)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by kelemen** [comment]
It seems that you are adding a component from a library defined in *Tools/Libraries*. That part of NB works only with Ant project. I'm not sure how to do it for Gradle projects (but I assume what works for Maven will work for Gradle) because I have never done this.
