### ISSUE TITLE
Netbeans 10/JDK11

### ISSUE THREAD

**Issue by qcsoftware513** [kelemen/netbeans-gradle-project#401]
I am having issues trying to use the plugin ON Netbeans 10/JDK 11.  

- "Background scanning of projects" hangs at 96%
- Trying to run custom task using hotkey F11 locks up IDE
- CPU usage spikes

I would be happy to give more details, but not sure what would be helpful.  Please let me know how I can provide more information.

**Comment by qcsoftware513** [comment]
i will add, apparently, Ctrl+S to save also locked up the ide.

**Comment by kelemen** [comment]
Which version do you tested this with? [10.0-vc3](https://dist.apache.org/repos/dist/dev/incubator/netbeans/incubating-netbeans/incubating-10.0-vc3)?

**Comment by qcsoftware513** [comment]
yes, VC3.

**Comment by qcsoftware513** [comment]
Oh - and I am running gradle 4.10.2

**Comment by qcsoftware513** [comment]
How do I do that?

Mike Billman
QC Software
+1-513-469-1424

Sent from my iPhone

On Nov 6, 2018, at 5:26 PM, Attila Kelemen <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm unable to reproduce the issue. Can you provide a thread dump, so that I can check where it is hanging?

**Comment by kelemen** [comment]
This should work: http://wiki.netbeans.org/GenerateThreadDump

**Comment by kelemen** [comment]
Or if NB UI is not frozen, you might click the profile IDE button and save from there (that is actually better).

**Comment by kelemen** [comment]
Or if somehow none of those work, you could use [jstack](https://docs.oracle.com/javase/7/docs/technotes/tools/share/jstack.html) given that NB is just a Java project.

**Comment by qcsoftware513** [comment]
Looks like an out of memory error.  Here is the output from console.
Mike

**Comment by kelemen** [comment]
I had an out of memory too when starting NB for some reason but I immedietally added *-Xmx2048m* to *ets/netbeans.conf* and it worked fine after that.

**Comment by qcsoftware513** [comment]
This is currently in netbeans.conf:

netbeans_default_options="-J-XX:+UseStringDeduplication -J-Xss2m -J-Xms32m -J-Djdk.gtk.version=2.2 -J-Dapple.laf.useScreenMenuBar=true -J-Dapple.awt.graphics.UseQuartz=true -J-Dsun.java2d.noddraw=true -J-Dsun.java2d.dpiaware=true -J-Dsun.zip.disableMemoryMapping=true -J-Dplugin.manager.check.updates=false -J-Dnetbeans.extbrowser.manual_chrome_plugin_install=yes -J--add-opens=java.base/java.net=ALL-UNNAMED -J--add-opens=java.base/java.lang.ref=ALL-UNNAMED -J--add-opens=java.base/java.lang=ALL-UNNAMED -J--add-opens=java.base/java.security=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing.text=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing=ALL-UNNAMED -J--add-opens=java.desktop/java.awt=ALL-UNNAMED -J--add-opens=java.desktop/java.awt.event=ALL-UNNAMED -J--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED -J--add-opens=jdk.jshell/jdk.jshell=ALL-UNNAMED -J--add-modules=jdk.jshell -J--add-exports=java.desktop/sun.awt=ALL-UNNAMED -J--add-exports=java.desktop/java.awt.peer=ALL-UNNAMED -J--add-exports=java.desktop/com.sun.beans.editors=ALL-UNNAMED -J--add-exports=java.desktop/sun.swing=ALL-UNNAMED -J--add-exports=java.desktop/sun.awt.im=ALL-UNNAMED -J--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED -J--add-exports=java.management/sun.management=ALL-UNNAMED -J--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED -J--add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED -J-XX:+IgnoreUnrecognizedVMOptions"

so is this added as follows:

-J-Xmx2048m

If so, I’ll give another try.

Mike

**Comment by kelemen** [comment]
Yes, you should add *-J-Xmx2048m* somewhere (or whatever value, I just happened to add this).

**Comment by qcsoftware513** [comment]
I hope to test this today.  Will let you know the results.

Mike

**Comment by qcsoftware513** [comment]
Trying this now…

On a related note…I am also getting error on every line of code (although build is successful).  I show can’t find “unable to find package java.lang in classpath or bootclasspath” on all files…trying a couple of other things to rule out…any ideas on that one?

Mike

**Comment by qcsoftware513** [comment]
Ok…so cleaned up the cache, but still no luck…

We are at the same behavior as previously…background scanning stops at 96% and saving a file locks up the IDE completely.  I had to use jstack to get the thread dump (attached).

Mike

From: Mike Billman
Sent: Monday, November 12, 2018 7:58 AM
To: 'kelemen/netbeans-gradle-project' <reply@reply.github.com>; kelemen/netbeans-gradle-project <netbeans-gradle-project@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [kelemen/netbeans-gradle-project] Netbeans 10/JDK11 (#401)

Trying this now…

On a related note…I am also getting error on every line of code (although build is successful).  I show can’t find “unable to find package java.lang in classpath or bootclasspath” on all files…trying a couple of other things to rule out…any ideas on that one?

Mike

**Comment by kelemen** [comment]
I don't think this is the fault of this plugin as the stack trace indicates an infinite recursion in nb-javac. So, the problem appears because of the presence of a certain project on which it "crashes".

**Comment by qcsoftware513** [comment]
What would your suggestion be at this point, then?  Should I report to NB team?  Try to reproduce with a non-gradle project?

Mike

**Comment by kelemen** [comment]
Yes, I think this should be reported to the NB team but they will also need a sample project on which NB crashes.

**Comment by qcsoftware513** [comment]
I created a new user directory and started over…I did not install nb-javac, and now I get this error…would this be expected?

Issue 1
--------

  Requested project: C:\Sandboxes\mdb\Products

  Stack trace:
    java.lang.ExceptionInInitializerError
                at org.gradle.tooling.GradleConnector.newConnector(GradleConnector.java:85)
                at org.netbeans.gradle.project.model.GradleConnectorRef.open(GradleConnectorRef.java:44)
                at org.netbeans.gradle.project.model.DefaultGradleModelLoader.createGradleConnectorRef(DefaultGradleModelLoader.java:145)
                at org.netbeans.gradle.project.model.DefaultGradleModelLoader.createGradleConnector(DefaultGradleModelLoader.java:141)
                at org.netbeans.gradle.project.model.DefaultGradleModelLoader.loadModelWithProgress(DefaultGradleModelLoader.java:538)
                at org.netbeans.gradle.project.model.DefaultGradleModelLoader.access$1600(DefaultGradleModelLoader.java:64)
                at org.netbeans.gradle.project.model.DefaultGradleModelLoader$6.run(DefaultGradleModelLoader.java:419)
                at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:35)
                at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:22)
                at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:125)
                at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
                at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
                at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
                at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:919)
                at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:898)
                at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:815)
                at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:827)
                at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:861)
                at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
                at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.IllegalArgumentException: Could not determine java version from '11.0.1'.
                at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
                at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
                at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.javaDeprecationWarning(UnsupportedJavaRuntimeException.java:36)
                at org.gradle.tooling.internal.consumer.ConnectorServices.checkJavaVersion(ConnectorServices.java:63)
                at org.gradle.tooling.internal.consumer.ConnectorServices.<clinit>(ConnectorServices.java:38)
                ... 20 more

**Comment by kelemen** [comment]
This error means, that you have tried loading a project with older Gradle version which does not support Java 11. It has nothing to do with NB (maybe this plugin but definitely not a general NB issue).

**Comment by qcsoftware513** [comment]
I probably will not get to this anytime soon as I have no time to put together a project that crashes (at least I doubt it) and have it be like the current one that crashes due to this being company proprietary project.

Mike

**Comment by qcsoftware513** [comment]
Yeah I just realized this…updated plugin and trying to run without nb-javac installed.

Mike

**Comment by qcsoftware513** [comment]
Still no progress in being able to reproduce in a project outside of the company code.  I think it is one/some of the dependencies but not sure.

**Comment by qcsoftware513** [comment]
For what it's worth, the problem seems to get much worse when I add the following dependency:

'org.apache.cxf:apache-cxf:3.1.0'

I hope this helps.  I still can't seem to reproduce unless i have all of our internal code.

**Comment by Angular-Angel** [comment]
I have this same problem in 12.6. Seems to be related to mixed groovy/java code in a gradle project.

**Comment by Angular-Angel** [comment]
Or maybe just groovy code at all. It has the same problem even when I move the java code to a separate directory.

**Comment by kelemen** [comment]
Are you sure you are using this plugin? NetBeans has its own built-in Gradle plugin for quite a while now.

**Comment by Angular-Angel** [comment]
Oh, you're right, I'm not! My bad, I thought this was just the netbeans repo for some reason.
