### ISSUE TITLE
NPE at project opening

### ISSUE THREAD

**Issue by makiam** [kelemen/netbeans-gradle-project#409]
Steps to reproduce:
Product Version: Apache NetBeans IDE Dev (Build 20180616-462079a28a6f)
Java: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01
Gradle: 5
I try to open spring-boot-web-application  project from https://github.com/pkainulainen/gradle-examples.git and see this exception:
java.lang.NullPointerException
	at org.netbeans.gradle.project.model.issue.ModelLoadIssueReporter.getImportantCause(ModelLoadIssueReporter.java:262)
	at org.netbeans.gradle.project.model.issue.ModelLoadIssueReporter.reportDependencyResolutionFailures(ModelLoadIssueReporter.java:281)
	at org.netbeans.gradle.project.model.issue.ModelLoadIssueReporter.lambda$reportDependencyResolutionFailures$3(ModelLoadIssueReporter.java:315)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
...
Exception occurs only once after IDE start and open project

**Comment by kelemen** [comment]
It seems it is a bug in the Spring Boot plugin used by the project. Probably, the Spring Boot plugin should be updated. That said, there is a bug in in this plugin as well which prevents to display the error. I'll fix it soon. For now, you can check your IDE log for the actual error's stack trace.

**Comment by kelemen** [comment]
I have fixed the issue both on the *nb81* and the *master* branches.
